id: P008039
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6061
  title: ཏིབེཏན་ཨེལེམེནཏལ་དིབི༹ནཏིཨོན་པཻནཏིངས
  author: ''
  volumes:
    f023e63ca6894b2a91f1f82297d894c9:
      image_group_id: I1KG6078
      title: 'Volume 1 of tibetan elemental divination paintings : illuminated manuscripts
        from the white beryl of sangs-rgyas rgya-mtsho with the moonbeams treatise
        of lo-chen dharmasri'
      volume_number: 1
      total_pages: 436
      base_file: v001.txt
ebook_metadata:
  title: ཏིབེཏན་ཨེལེམེནཏལ་དིབི༹ནཏིཨོན་པཻནཏིངས
  author: ''
  sku: P008039
  cover: cover.jpg
  layers:
  - pagination
