id: P008039
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6061
  title: ཏིབེཏན་ཨེལེམེནཏལ་དིབི༹ནཏིཨོན་པཻནཏིངས
  author: ''
  volumes:
    e081769f45a949ce9e230ccd42c528b6:
      image_group_id: I1KG6078
      title: ''
      volume_number: 1
      total_pages: 436
ebook_metadata:
  title: ཏིབེཏན་ཨེལེམེནཏལ་དིབི༹ནཏིཨོན་པཻནཏིངས
  author: ''
  sku: P008039
  cover: cover.jpg
  layers:
  - pagination
