id: I9C5809EE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:26:50+00:00'
last_modified: '2022-06-08T17:59:52.142796+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6061
  title: ཏིབེཏན་ཨེལེམེནཏལ་དིབི༹ནཏིཨོན་པཻནཏིངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '1986':
      image_group_id: I1KG6078
      title: 'Volume 1 of tibetan elemental divination paintings : illuminated manuscripts
        from the white beryl of sangs-rgyas rgya-mtsho with the moonbeams treatise
        of lo-chen dharmasri'
      total_pages: 436
      order: 1
      base_file: 1986.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
